### ISSUE TITLE
Consider removing ”Important information” box

### ISSUE THREAD

**Issue by hidde** [w3c/wai-course-list#11]
I would remove the “Important Disclaimer” box. I'm unconvinced that the phrase “offers are user-submitted, not W3C-endorsed” misses any important aspect. Below I have added some analysis for each sentence to support that point.

“W3C does not endorse specific vendor products. Inclusion of products in this list does not indicate endorsement by W3C. ” this says the same thing twice, and is in itself already captured by “not W3C-endorsed“ above 

“The information can change at any time.” this is the case for the web at large and not something that needs disclaiming (unless this page looks like it is a law or standard (eg a /TR page), which it doesn't)

“Offer descriptions, search criteria, and other information in this database is provided by offers providers. ” - this is already captured in “are user-submitted”

“Products and search criteria are listed with no quality rating.“ - this is not implied anywhere, there is no meta data that says “Quality” or anything that suggests quality rating has been done. 

“The list is not a review of offers, nor a complete or definitive list of all offers.”. - “not a review of offers”, see above, I feel this is similar to “no quality rating”.  “nor a complete or definitive list of all offers” - if we're really worried about this, why not add to the sentence at the top: “offers are user-submitted, not W3C-endorsed. This list is not complete”

**Comment by leticiaseixas** [comment]
The disclaimer provided follows other WAI resources and, for this, we believe any further improvements or updates on this disclaimer should be brought to a higher level of discussion. We will include a review of this disclaimer as an open issue since other similar resources are currently being updated, this would be a good opportunity to evaluate whether any changes are necessary in a broader context.
