### ISSUE TITLE
(low) [Listing page] Website field necessary in Details

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-course-list#113]
The Website fields seems to just repeat what is in the course title. Just wondering if it is a bit redundant?

**Comment by leticiaseixas** [comment]
This field is repeated for three main reasons:
- It is presented right at the beginning without the need to open the course details.
- Since this is a long list, it is also available at the end, so users don't need to go back to the top to get this information.
- To help with context with the link to the reviews page.

Considering that, is it enough just to keep it at the top or bottom?

**Comment by iadawn** [comment]
The only problem I thought about it was it was a bare URL link which could be avoided. Other than that, it wasn't really an issue.

**Comment by leticiaseixas** [comment]
Given that the label for this information is a website, we consider that a URL is to be expected. Any thoughts on how to present this in a different way?

**Comment by iadawn** [comment]
Honestly, no 😁. That was one of the reasons why I thought to just remove it. This is low priority though and I don't have any strong thoughts about it
