### ISSUE TITLE
"offers" is an awkward term

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-course-list#12]
Since the title is List of Courses, why not just use courses? I understand that there are other types of resources in the list so if courses is insufficient, maybe use "resources"

**Comment by iadawn** [comment]
+1

**Comment by bakkenb** [comment]
I agree that "offers" is just a little awkward. Some areas it is okay, but problematic or odd especially in other places that it is used, such as the following:

Submission Page:
- "Submit a course, training, or certification offer"
- "Offers providers can use this form to add..."
- "Indicate the type of the offer."

Since the resource title is currently "List of Accessibility Courses: Education, training, and certification", the main word used to describe all these offerings is "Courses" so I would be more inclined to just use the term courses in a broad sense throughout the resource.

**Comment by eoncins** [comment]
+1 to use "Courses" and if this is not enough maybe use "submit a course or training" which in my opinion are the two different options. In terms of certification it can apply to a course or a training.

**Comment by leticiaseixas** [comment]
We removed the word "offer" when not necessary through the resource. In cases it was needed to define it, we used "course, training, and certification", resource, or submission, according to the context.
