### ISSUE TITLE
'Learning' options are unclear

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-course-list#14]
I think the terms: guided, non-guided, synchronous and asynchronous are a bit unclear.

Some suggested alternatives:

* Tutor led
* Self-directed
* Scheduled sessions
* At your own pace

Last one is a bit off

**Comment by sharronrush** [comment]
+1 to need for clarity, uncertain of correct terms

**Comment by bakkenb** [comment]
Agree some refinement here is needed. 
More ideas:

- Self paced
- Instructor led
- Scheduled
- Interactive (asynchronous but there is a leader/instructor involved)(may interact with other students/participants)
- Non-interactive (asynchronous with no leader/instructor involved)

Maybe each option used for this list could come with a very short definition.

**Comment by eoncins** [comment]
Teaching formats may need an explanation, specially to clarify the term HYBRID.
HYBRID can also be a blended format (mix of online and face-to-face activities). We call it "semi-presential" and with the current format of the submission is not possible to indicate it. 
I understand GUIDED as Tutor/Instructor led. Another thing NON-GUIDED because it can be scheduled of self paced. So maybe including SELF PACED, as in the case of a MOOC, can be a solution.
Another issue is the learning synchronous and asynchronous need to be explained. In our project IDE@ we offer the following definitions:
SYNCHRONOUS TEACHING is online distance education that happens in real-time, often with a set class schedule and required login times. ASYNCHRONOUS TEACHING does not require real-time interaction; instead, content is available online for learners to access when it best suits their schedules, and assignments are completed according to deadlines. Online teaching can also use a BLENDED teaching model, which includes mixed synchronous and asynchronous activities.

**Comment by vmmiller** [comment]
Suggest using clear terms, e.g.:

"Indicate the type of learning provided in this offer. Sessions will be:
- led an instructor according to a fixed program
- self-paced 
- scheduled at your own pace but within a defined time frame
- hybrid (partly guided by an instructor, partly according to your own pace)"
