### ISSUE TITLE
sort by not working

### ISSUE THREAD

**Issue by leticiaseixas** [w3c/wai-course-list#292]
In `courses/list/` (development branch) change the `Sort Order` 

List is not redrawn and should be

**Comment by SteveALee** [comment]
@leticiaseixas The reason is your [sorting function](https://github.com/w3c/wai-course-list/blob/development/_includes/wai-course-list/js/courses.js#L201) is comparing the data title with the ID in the DOM and that doesn't do what you want.

I guess you could either extract the Title from the Heading link (assuming it is the same as the data title) or attach the data title as a data attribute?

**Comment by SteveALee** [comment]
PS I also noticed that the `rebuildList` function [mutates the the array that is passed in](https://github.com/w3c/wai-course-list/blob/development/_includes/wai-course-list/js/courses.js#L198). Thats doesnl;t seem to matter here as `newResults` is [not used again](https://github.com/w3c/wai-course-list/blob/development/_includes/wai-course-list/js/courses.js#L96-L101) in the calling function.

Personally though, I'd make the function pure, most likely by making a copy of the array to work with (using either  ... or slice)

HTH
